<template><div><p>发布 <code v-pre>npm</code> 包的详细流程以及可能会遇到的问题。</p>
<!-- more -->  
<h2 id="_1-初始化文件" tabindex="-1"><a class="header-anchor" href="#_1-初始化文件"><span>1. 初始化文件</span></a></h2>
<p>创建一个空文件夹 <code v-pre>npm-demo</code> ，并创建以下文件：</p>
<div class="vp-file-tree"><ul>
<FileTreeItem type="folder" :expanded="true" :empty="false"><span class="tree-node folder"><VPIcon name="vscode-icons:default-folder"></VPIcon><span class="name">npm-demo</span></span>
<ul>
<FileTreeItem type="file" :expanded="false" :empty="true"><span class="tree-node file"><VPIcon name="vscode-icons:file-type-node"></VPIcon><span class="name">package.json</span><span class="comment">配置文件</span></span></FileTreeItem>
<FileTreeItem type="file" :expanded="false" :empty="true"><span class="tree-node file"><VPIcon name="vscode-icons:file-type-js"></VPIcon><span class="name">index.js</span><span class="comment">文件入口</span></span></FileTreeItem>
<FileTreeItem type="file" :expanded="false" :empty="true"><span class="tree-node file"><VPIcon name="flat-color-icons:info"></VPIcon><span class="name">README.md</span><span class="comment">包说明文档</span></span></FileTreeItem>
</ul>
</FileTreeItem>
</ul>
</div><h3 id="_1-1-package-json" tabindex="-1"><a class="header-anchor" href="#_1-1-package-json"><span>1.1 package.json</span></a></h3>
<p>你可以使用命令根据 <code v-pre>配置向导</code> 来创建这个文件：</p>
<div class="language-shell" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> init</span></span></code></pre>
</div><p>若觉得过程太繁琐你可以自己创建这个文件，并在文件里写写好以下基本配置：</p>
<div class="language-json line-numbers-mode" data-highlighter="shiki" data-ext="json" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">{</span></span>
<span class="line"><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">  "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">name</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">包名</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">  "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">version</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">版本号，如 1.0.0</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">  "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">description</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">包描述</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">  "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">main</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">入口文件相对路径</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">  "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">keywords</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#999999;--shiki-dark:#666666"> [</span></span>
<span class="line"><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">    "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">关键字1</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">    "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">关键字2</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">  ],</span></span>
<span class="line"><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">  "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">author</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">作者</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">,</span></span>
<span class="line"><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">  "</span><span style="--shiki-light:#998418;--shiki-dark:#B8A965">license</span><span style="--shiki-light:#99841877;--shiki-dark:#B8A96577">"</span><span style="--shiki-light:#999999;--shiki-dark:#666666">:</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">开源协议</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-dark:#666666">}</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_1-2-入口文件" tabindex="-1"><a class="header-anchor" href="#_1-2-入口文件"><span>1.2 入口文件</span></a></h3>
<p><code v-pre>main</code> 字段的值是程序的主要入口点（默认是 <code v-pre>index.js</code>）。
也就是说，如果我们的包名为 <code v-pre>npm-test</code>，当其他开发者安装这个包，
<code v-pre>import 'npm-test'</code> 方式导入，那么 <code v-pre>npm-test</code> 包中
<code v-pre>package.json</code> 中的 <code v-pre>main</code> 的导出对象将被返回。</p>
<h3 id="_1-3-readme-md" tabindex="-1"><a class="header-anchor" href="#_1-3-readme-md"><span>1.3 README.md</span></a></h3>
<p><code v-pre>README.md</code> 为对包的描述，可对包的安装及其使用做出说明。这个文件是非必要文件，<strong>可以不创建</strong>。</p>
<div class="language-markdown" data-highlighter="shiki" data-ext="markdown" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#999999;--shiki-light-font-weight:bold;--shiki-dark:#666666;--shiki-dark-font-weight:bold">##</span><span style="--shiki-light:#1C6B48;--shiki-light-font-weight:bold;--shiki-dark:#4D9375;--shiki-dark-font-weight:bold"> 安装</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#999999;--shiki-light-font-weight:bold;--shiki-dark:#666666;--shiki-dark-font-weight:bold">##</span><span style="--shiki-light:#1C6B48;--shiki-light-font-weight:bold;--shiki-dark:#4D9375;--shiki-dark-font-weight:bold"> 用法说明</span></span></code></pre>
</div><h2 id="_2-发布" tabindex="-1"><a class="header-anchor" href="#_2-发布"><span>2. 发布</span></a></h2>
<p>在这之前需要前往 <a href="https://www.npmjs.com/" target="_blank" rel="noopener noreferrer">npm</a> 注册一个账号。
使用 <code v-pre>npm login</code> 登录：</p>
<div class="language-shell" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> login</span></span></code></pre>
</div><p>输入命令后会要求输入 <code v-pre>Username</code> ，随后会跳转一个登录链接，根据提示登录即可。
再使用 <code v-pre>npm publish</code> 发布：</p>
<div class="language-shell" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> publish</span></span></code></pre>
</div><p>当控制台出现 <code v-pre>npm notice Publishing to https://www.npmjs.com/ ...</code> 则发布成功。</p>
<h2 id="_3-问题" tabindex="-1"><a class="header-anchor" href="#_3-问题"><span>3. 问题</span></a></h2>
<p>以下为在过程中可能会遇到的问题与解决办法。</p>
<h4 id="登录无反应" tabindex="-1"><a class="header-anchor" href="#登录无反应"><span>登录无反应</span></a></h4>
<p>若输入 <code v-pre>npm login</code> 且输入 <code v-pre>Username</code> 后长时间无反应，则可能是 <code v-pre>npm</code> 使用了镜像地址，需要更改为官方地址。</p>
<div class="language-shell" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">#查看地址</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">pnpm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> config</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> get</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> registry</span></span>
<span class="line"><span style="--shiki-light:#A0ADA0;--shiki-dark:#758575DD">#更改为官方地址</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">pnpm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> config</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> set</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> registry</span></span></code></pre>
</div><h4 id="无法发布到私有包" tabindex="-1"><a class="header-anchor" href="#无法发布到私有包"><span>无法发布到私有包</span></a></h4>
<div class="language-shell" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ERR!</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> publish</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Failed</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> PUT</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 402</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ERR!</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> code</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> E402</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ERR!</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> You</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> must</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> sign</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> up</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> for</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> private</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> packages</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> :</span></span></code></pre>
</div><p>这个当你的包名为 <code v-pre>@Username/PackageName</code> 时才会出现，
原因是当包名 <code v-pre>@Username</code> 开头时，<code v-pre>npm publish</code> 会默认发布为私有包，
但是 <code v-pre>npm</code> 的私有包需要付费，所以需要添加如下参数进行发布:</p>
<div class="language-shell" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> publish</span><span style="--shiki-light:#A65E2B;--shiki-dark:#C99076"> --access</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> public</span></span></code></pre>
</div><h4 id="包名过于类似" tabindex="-1"><a class="header-anchor" href="#包名过于类似"><span>包名过于类似</span></a></h4>
<div class="language-shell" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ERR!</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> publish</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Failed</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> PUT</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 403</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ERR!</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> code</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> E403</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ERR!</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Package</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> name</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> too</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> similar</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> existing</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> packages</span><span style="--shiki-light:#999999;--shiki-dark:#666666">;</span><span style="--shiki-light:#59873A;--shiki-dark:#80A665"> try</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> renaming</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> your</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> package</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">@Username/PackageName</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> and</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> publishing</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> with</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> '</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">npm publish --access=public</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">'</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> instead</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> :</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> your-package</span></span></code></pre>
</div><p>如果 <code v-pre>npm</code> 上已经有了不少和你的包名类似的包，就会出现这个问题，在 <code v-pre>package.json</code> 中修改你的包名即可。</p>
<h4 id="没有权限发布" tabindex="-1"><a class="header-anchor" href="#没有权限发布"><span>没有权限发布</span></a></h4>
<div class="language-shell" data-highlighter="shiki" data-ext="shell" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ERR!</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> publish</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Failed</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> PUT</span><span style="--shiki-light:#2F798A;--shiki-dark:#4C9A91"> 403</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ERR!</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> code</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> E403</span></span>
<span class="line"><span style="--shiki-light:#59873A;--shiki-dark:#80A665">npm</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> ERR!</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> You</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> do</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> not</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> have</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> permission</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> to</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> publish</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77"> "</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">your-package</span><span style="--shiki-light:#B5695977;--shiki-dark:#C98A7D77">"</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D">.</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> Are</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> you</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> logged</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> in</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> as</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> the</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> correct</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> user?</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> :</span><span style="--shiki-light:#B56959;--shiki-dark:#C98A7D"> your-package</span></span></code></pre>
</div><p>包名和其他用户的包重名，<code v-pre>npm</code> 里的包不允许重名，，改个没有人用的包名即可。</p>
</div></template>


